
services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_network

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env

networks:
  inception_network:

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/sneshev/data/wordpress
      o: bind
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/sneshev/data/mariadb
      o: bind